---
title: "타당도: 은밀한 것을 찾아서 드러냄"
---

타당도는 교육 시험의 세계에서 가장 중요한 개념입니다. 이 책의 저자로서, 그리고 모든 장의 장점을 굳게 믿는 저는 여러분이 지금 시작하는 장이 이 책에서 가장 중요한 장의 산 정상에 홀로 서 있다고 확신할 수 있습니다. 각별한 주의를 기울여 읽어주시기를 간곡히 부탁드립니다.

타당도의 최고 중요성에 대한 지지의 설교를 펼치기 전에, 먼저 교육 및 심리 검사 표준을 개정한 평가 전문가들로 구성된 슈퍼스타 집단(AERA, APA, & NCME, 2014)의 외부 확인을 요청하고 싶습니다. 대부분의 교육 평가 전문가들이 성서처럼 여기는 공동 표준은 먼저 타당도를 "증거와 이론이 제안된 검사 용도에 대한 점수 해석을 뒷받침하는 정도"로 정의한 후, 이 판결을 내렸습니다:

따라서 타당도는 시험을 개발하고 시험을 평가할 때 가장 근본적으로 고려해야 할 사항입니다(11쪽).

물론 이 반박을 환영하지만, 이 문장에서 잠시 멈춰서 생각해 보시기를 권하고 싶습니다. 이는 이 장의 이해 기반 과제, 즉 평가 타당도가 무엇일 뿐만 아니라 왜 그것이 시험 제작과 시험 해석에 필수적인지 파악하는 것을 나타냅니다. 제가 스스로 내린 결론이자 여러분과 함께 나누고 싶은 결론은 타당도가 없다면 교육 시험은 아무런 의미도, 목적도, 정당한 적용도 없다는 것입니다. 이 장에서는 그 이유를 살펴보겠습니다.

## 비밀리에 대처하기

우리가 학생들을 가르치는 이유는 학생들이 무언가를 배우도록 하기 위해서입니다. '커리큘럼 목표', '교육 목표' 또는 '콘텐츠 표준'이라고도 하는 이 학습 내용은 일반적으로 인지 능력과 지식으로 구성됩니다. 이러한 기술과 지식에는 수학적 또는 과학적 사실과 절차, 문해력과 언어 능력, 시민 의식에 대한 지식, 과거를 이해하고 역사의 교훈을 미래에 적용하는 능력, 그리고 기본적으로 우리가 "학교 공부"라고 생각하는 모든 것이 포함됩니다. 때로는 체육 수업에서 추구하는 대근육 능력이나 컴퓨터 수업에서 장려하는 소근육 키보딩 능력과 같은 정신 운동 능력이 교육 목표에 포함되기도 합니다. 또한 일부 교사는 학생들이 언어에 대한 사랑, 과학적 호기심, 개방적이고 편견 없는 인간관 등 특정 정서적 성향을 습득하도록 하려고 노력합니다.

학생들의 기술, 지식, 정서의 습득을 촉진하는 일을 하는 교사와 학교 관리자는 그 일을 잘 수행하기를 원합니다. 그들은 자신의 교육적 노력이 성공하기를 원합니다. 그리고 평가는 교육자가 학생들이 추구하는 커리큘럼 목표를 달성했는지 파악할 수 있는 도구입니다. 하지만 여기서 문제가 발생합니다.

대부분의 경우 교사는 학생을 보고 학생이 실제로 배운 내용을 습득했는지 여부를 알 수 없습니다. 언젠가는 뇌에 초점을 맞춘 수술 및 방사선 촬영 절차의 발전으로 교사가 학생의 두개골 내부에 있는 기술과 지식을 실제로 볼 수 있게 될 것입니다. 그러나 당분간은 교육자들은 학생들이 학습한 것과 학습하지 않은 것의 은밀한 특성에 대해 충분히 정확한 추론을 하기 위해 학생들이 시험을 통해 얻은 명백한 증거에 의존해야 합니다.

이 장의 제목에서 알 수 있듯이, 교육자는 관찰 가능한 학생의 시험 반응을 사용하여 관찰할 수 없는 학생의 상태를 파악합니다. 독자 여러분, 이것이 바로 교육용 시험이 탄생한 이유이자 시험이 계속 존재하는 이유입니다. 시험이 이러한 역할을 수행하지 못한다면 모두의 시간을 낭비하는 것입니다. 타당도는 은밀한 것을 드러내는 테스트의 능력에 대한 자신감의 토대입니다.

서론이 끝났으니 이제 이 책에서 반드시 마스터해야 할 6가지 평가에 대한 이해 중 가장 중요한 첫 번째 내용을 소개하겠습니다.

> 타당도 이해
>
> 타당도란 시험 결과의 사용 제안에 대한 증거 기반 논증이 시험 해석의 정확성을 뒷받침하는 정도를 말하며, 모든 교육 평가의 필수 전제 조건입니다.
