# 서문 {.unnumbered}

제 사전에는 서문이란 "일반적으로 책의 주제, 범위 또는 목적을 서술하는" 책의 서론이라고 나와 있습니다. 그 말이 맞는 것 같습니다. 따라서 이 서문에서는 여러분이 읽으려는 책의 주제, 범위, 목표를 밝히겠습니다.

저는 그동안 많은 서문을 썼고, 그 길이도 상당히 다양합니다. 이 책은 우리나라의 교육 전문가인 교사와 교육행정가들에게 매우 중요한 내용을 다루고 있고, 여러분과 다른 모든 독자들이 지체 없이 책의 핵심을 파악할 수 있기를 바라기 때문에 대부분의 서문보다 짧게 쓰려고 합니다.

서문에 대해 사전에서 정의한 세 가지 작업을 먼저 살펴봅시다. 이 책의 주제는 교육 평가에 대한 최우선적인 이해, 즉 교육의 세계에서 일반적으로 측정에 기반한 실수의 수와 규모를 줄일 수 있는 이해의 집합입니다. 다시 말해, 이 책의 초점인 6가지 우선 순위가 높은 평가 진리를 이해하면 교육 시험의 오용으로 인해 발생하는 대부분의 교육적 오류를 줄이거나 완전히 없앨 수 있습니다.

이 책의 범위는 6가지의 이해에 집중하는 소박하지만, 그 영향력은 잠재적으로 방대합니다. 왜냐하면 이러한 이해는 교육 평가의 가장 기본적이고 진정으로 근본적인 개념과 절차이기 때문입니다. 이는 교육자가 매일 매일 내리는 결정과 직접적인 관련이 있습니다. 이러한 결정이 잘 내려지면 학생들이 받는 교육의 질이 향상됩니다.

마지막으로, 이 책의 목표는 교육자인 독자들이 가능한 한 빨리 '평가 문맹'이 되지 않도록 돕는 것입니다. 공정하게 말하자면, 제목에서 그 목표를 이미 드러냈습니다. "표지만 보고 책을 판단해서는 안 된다"는 속담은 사람들이 본질보다는 표면적인 요소에 의존하지 않도록 하기 위한 것입니다. 하지만 아직 읽지 않은 책이 첩보 소설이든 글루텐 프리 식사에 대한 안내서이든, 제목은 일반적으로 예비 독자에게 책 내용에 대한 한두 가지 단서를 제공합니다. 현재 손에 쥐고 있는 책도 마찬가지입니다.

2017년, Neil deGrasse Tyson은 우주에 대한 기본적인 질문들에 초점을 맞춘 책 '급한 사람들을 위한 천체물리학'을 출간했습니다. Tyson은 매혹적인 주제에 대해 우아하고 명료하게 글을 쓰는 저명한 권위자이기 때문에 자연스럽게 이 책은 많은 베스트셀러 목록에서 높은 순위에 올랐습니다. 그리고 Tyson 교수의 타깃 독자인 '급한 사람들'은 제가 아는 거의 모든 교사와 관리자를 설명하는 말이기 때문에 제목에 그 부분을 집어넣는 것이 좋겠다고 생각했습니다. Tyson 교수님께는 죄송하지만, 저는 교육 평가가 그 어떤 답답한 천체 물리학 책보다 인류에게 훨씬 더 흥미롭고 관련성이 있다고 생각합니다.

'당신'이라는 호칭은 제가 교수님을 알고 있다는 것을 전제로 한 것입니다. 물론 저는 잘 모르지만, 이런 종류의 책을 쓰기로 결심했을 때 제가 상상했던 대상은 이미 현직 교육자, 즉 교사와 장학사를 포함한 교육행정가였습니다. 저는 대부분 시험에 대한 공식적인 교육을 받은 적이 없는 오늘날의 교육자들에게 교육 평가의 기본을 다루는 짧고 읽기 쉬운 책이 필요하다고 확신했습니다. 제가 염두에 둔 또 다른 독자층은 운 좋게도 교육이나 시험에 초점을 맞춘 정규 과정에 등록할 수 있는 신규 교사들이었습니다. 후자에 해당한다면, 평가 리터러시를 통해 긍정적인 빛을 발하며 교단에 서게 될 것이고, 앞으로 가르치게 될 학생들도 훨씬 더 나은 사람이 될 것이라고 확신합니다.

이 책에서 제가 취한 접근 방식은 교육자로서의 제 경험을 반영한 것입니다. 저는 소규모 대학에서 학사 및 석사 학위를 취득한 후 오리건주 시골에서 고등학교 교사로 2년간 근무했습니다. 하지만 저는 제 인생의 대부분을 대학 교수로 보냈습니다. 따라서 설명이 필요해 보이는 주제에 대해 글을 쓸 때면, 제 본능적인 성향은 성가시리도록 교수적인 태도를 취하고 가끔씩 주의 깊은 대학생들에게 강의하듯 장황한 설명을 늘어놓는 것입니다. 저는 이 책에서 그런 교수의 모습을 일부러 버렸습니다. 교수 휴게실에서 동료와 대화를 나누는 것처럼 모든 설명을 구성하고, 수십 년간 교수로 일하면서 생긴 교수적 성향, 즉 횡설수설하는 습관을 억제하려고 노력했습니다.

서문의 역할에 대한 사전의 간결한 정의에 따라 그렇게 할 필요는 없지만, 제가 ASCD를 위해 쓴 여섯 권의 책에서 제 말이 제대로 작동하도록 한결같이 멋진 작업을 해준 ASCD 편집자 Katie Martin에게 감사의 말을 전하고 싶습니다. 언제나 그렇듯이 저는 그녀에게 박수와 감사를 표합니다.

W.J.P

July 2018
